# pandas

In [16]:
import pandas as pd

print(pd.__version__)

3.0.2

## panda series

### A Pandas Series is like a column in a table.

*It is a one-dimensional array holding data of any type.*

In [17]:
a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

- **With the index argument, you can name your own labels.**

In [18]:
a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [19]:
print(myvar["y"])

7

In [20]:
lst = [1,2,3,4,5,6]
print(lst)
series = pd.Series(lst)
print(series)
print(type(series))

[1, 2, 3, 4, 5, 6]
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.Series'>

In [21]:
a = pd.Series(['p','q','r','s','t'], index = [10,11,12,13,14])
a

10    p
11    q
12    r
13    s
14    t
dtype: str

In [22]:
b = pd.Series(['p','q','r','s','t'], index = [10,11,12,13,14], name = 'alphabets')
b

10    p
11    q
12    r
13    s
14    t
Name: alphabets, dtype: str

In [23]:
scalar_series = pd.Series(0.5, index = [1,2,3])
scalar_series

1    0.5
2    0.5
3    0.5
dtype: float64

- **You can also use a key/value object, like a dictionary, when creating a Series.**

In [24]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

- **The keys of the dictionary become the labels.**

In [25]:
print(myvar['day1'])

420

- **To select only some of the items in the dictionary, use the index argument and specify only the items you want to include in the Series.**

In [26]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [27]:
dict_series = pd.Series({'p':[1,5,6], 'q':[2,6,7], 'r':[3,9,0], 's':[4,4,5], 't':[5,1,2]})
dict_series

p    [1, 5, 6]
q    [2, 6, 7]
r    [3, 9, 0]
s    [4, 4, 5]
t    [5, 1, 2]
dtype: object

## Data Frames

- Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

   *Series is like a column, a DataFrame is the whole table.*

In [28]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [29]:
lst = [1,2,3,4,5]
df = pd.DataFrame(lst)
df

   0
0  1
1  2
2  3
3  4
4  5

In [30]:
lst = [[1,2,3,4,5], [11,12,13,14,15]]
df = pd.DataFrame(lst)
df

    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [31]:
a = [{'a':5, 'b':7, 'c':9, 'd':2}, 
     {'a':4, 'b':8, 'c':19, 'd':12}]        # Dictionary Keys represents Column names

df = pd.DataFrame(a)
df

   a  b   c   d
0  5  7   9   2
1  4  8  19  12

In [32]:
b = {'RollNo.':pd.Series([1,2,3,4,5]), 
    'Maths':pd.Series([67,89,23,90,56]), 
    'Physics':pd.Series([12,98,44,90,78])}      

df = pd.DataFrame(b)
df

   RollNo.  Maths  Physics
0        1     67       12
1        2     89       98
2        3     23       44
3        4     90       90
4        5     56       78

In [33]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

### Locate Row
*Pandas use the loc attribute to return one or more specified row(s)*

In [34]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [35]:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

*When using [ ], the result is a Pandas DataFrame.*

In [36]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [37]:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64

### Load Files Into a DataFrame

In [38]:
df = pd.read_csv('pokemon_data.csv')

print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'pokemon_data.csv'

In [ ]:
df = pd.read_csv(r'C:\Users\Admin\Desktop\PythonProject\pandastutorial\Datasets\Salary_Data.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Desktop\\PythonProject\\pandastutorial\\Datasets\\Salary_Data.csv'

### Dataframe functions

In [43]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ravitejakotharu/salary-datacsv")

print("Path to dataset files:", path)

Path to dataset files: /Users/tony/.cache/kagglehub/datasets/ravitejakotharu/salary-datacsv/versions/1

In [46]:
df = pd.read_csv(r'/Users/tony/.cache/kagglehub/datasets/ravitejakotharu/salary-datacsv/versions/1/Salary_Data.csv')

In [47]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='str')

In [ ]:
df.shape

In [ ]:

df.size

In [ ]:
df.head()

In [ ]:
df.head(2)

In [ ]:
df.tail()

In [ ]:
df.tail(8)

In [ ]:
df.describe()

In [ ]:
df.info()

## Handling missing values

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohithmahadevan/students-marksheet-dataset")

print("Path to dataset files:", path)

Path to dataset files: /Users/tony/.cache/kagglehub/datasets/mohdshahnawazaadil/restaurant-dataset/versions/1

In [92]:
df = pd.read_csv(r'/Users/tony/.cache/kagglehub/datasets/rohithmahadevan/students-marksheet-dataset/versions/1/marksheet.csv')
df.head()

   id     Name  Gender  Age Section  Science  English  History  Maths
0   1  Bronnie  Female   13       C       21       81       62     49
1   2   Lemmie    Male   15       B       29       41       17     40
2   3    Danya  Female   14       C       12       87       16     96
3   4    Denna  Female   14       B       15       53       82     33
4   5  Jocelin    Male   14       A       43        6        3     21

In [93]:
df.isnull()

        id   Name  Gender    Age  Section  Science  English  History  Maths
0    False  False   False  False    False    False    False    False  False
1    False  False   False  False    False    False    False    False  False
2    False  False   False  False    False    False    False    False  False
3    False  False   False  False    False    False    False    False  False
4    False  False   False  False    False    False    False    False  False
..     ...    ...     ...    ...      ...      ...      ...      ...    ...
245  False  False   False  False    False    False    False    False  False
246  False  False   False  False    False    False    False    False  False
247  False  False   False  False    False    False    False    False  False
248  False  False   False  False    False    False    False    False  False
249  False  False   False  False    False    False    False    False  False

[250 rows x 9 columns]

In [94]:
df.isnull().sum()

id         0
Name       0
Gender     0
Age        0
Section    0
Science    0
English    0
History    0
Maths      0
dtype: int64

In [95]:
df.isnull().sum().sum()

np.int64(0)

### dropping rows with NaN values

In [96]:
df.shape

(250, 9)

In [97]:
df2 = df.dropna()     # default axis = 0

In [98]:
df2.shape

(250, 9)

### Dropping Columns with NaN values

In [99]:
df3 = df.dropna(axis = 1)

In [100]:
df3.shape

(250, 9)

In [101]:
df.dropna(how = 'any')    # if any row value is null then remove that row

      id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie  Female   13       C       21       81       62     49
1      2    Lemmie    Male   15       B       29       41       17     40
2      3     Danya  Female   14       C       12       87       16     96
3      4     Denna  Female   14       B       15       53       82     33
4      5   Jocelin    Male   14       A       43        6        3     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie    Male   13       C       28       15       25     10
246  247       Rog  Female   13       B        1        4       68     65
247  248      Kaia    Male   15       B       93       48       82     44
248  249      Anni  Female   14       B       35       73       66     59
249  250  Fernande    Male   15       B       50        8       80     78

[250 rows x 9 columns]

In [102]:
df.dropna(how = 'all')    # if all row values is null then remove that row

      id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie  Female   13       C       21       81       62     49
1      2    Lemmie    Male   15       B       29       41       17     40
2      3     Danya  Female   14       C       12       87       16     96
3      4     Denna  Female   14       B       15       53       82     33
4      5   Jocelin    Male   14       A       43        6        3     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie    Male   13       C       28       15       25     10
246  247       Rog  Female   13       B        1        4       68     65
247  248      Kaia    Male   15       B       93       48       82     44
248  249      Anni  Female   14       B       35       73       66     59
249  250  Fernande    Male   15       B       50        8       80     78

[250 rows x 9 columns]

In [103]:
df.dropna(inplace = True)

In [104]:
df.shape

(250, 9)

## Filling the Null values

In [105]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vicky1999/student-marks-dataset")

print("Path to dataset files:", path)

Path to dataset files: /Users/tony/.cache/kagglehub/datasets/vicky1999/student-marks-dataset/versions/1

In [106]:
df=pd.read_csv(r'/Users/tony/.cache/kagglehub/datasets/vicky1999/student-marks-dataset/versions/1/Student.csv')
df.head()

   Maths  Physics  Chemistry  Result
0     17       27         22       0
1     72       82         77       1
2     97       18         13       0
3      8       42         37       0
4     32       25         20       0

In [107]:
df.isnull().sum()

Maths        0
Physics      0
Chemistry    0
Result       0
dtype: int64

In [108]:
df.fillna(0)

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

In [109]:
df.fillna(2)

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

In [110]:
df.fillna({'Physics':'none', 'Chemistry':0, 'Maths':30})

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

In [112]:
df.fillna( method = 'bfill')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [ ]:
df['Physics'].fillna(value=df['Physics'].mean())

0      27
1      82
2      18
3      42
4      25
       ..
995    48
996    22
997    64
998    41
999    74
Name: Physics, Length: 1000, dtype: int64

In [ ]:
df.fillna(method = 'bfill', inplace = True)

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

## replace

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohithmahadevan/students-marksheet-dataset")

print("Path to dataset files:", path)

Downloading to /Users/tony/.cache/kagglehub/datasets/rohithmahadevan/students-marksheet-dataset/1.archive...

100%|██████████| 3.76k/3.76k [00:00<00:00, 1.95MB/s]

Extracting files...
Path to dataset files: /Users/tony/.cache/kagglehub/datasets/rohithmahadevan/students-marksheet-dataset/versions/1

In [ ]:
df = pd.read_csv(r'/Users/tony/.cache/kagglehub/datasets/rohithmahadevan/students-marksheet-dataset/versions/1/marksheet.csv')
df.head()

   id     Name  Gender  Age Section  Science  English  History  Maths
0   1  Bronnie  Female   13       C       21       81       62     49
1   2   Lemmie    Male   15       B       29       41       17     40
2   3    Danya  Female   14       C       12       87       16     96
3   4    Denna  Female   14       B       15       53       82     33
4   5  Jocelin    Male   14       A       43        6        3     21

In [113]:
df.replace(to_replace=26, value=30)

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

In [114]:
df.replace(34, 10000)

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

In [115]:
df.replace(to_replace=[50,51,52,53,54,55,56,57,58,59], value= 'A')

    Maths Physics Chemistry  Result
0      17      27        22       0
1      72      82        77       1
2      97      18        13       0
3       8      42        37       0
4      32      25        20       0
..    ...     ...       ...     ...
995     4      48        64       0
996    63      22        88       0
997    90      64        43       1
998    67      41         6       0
999    92      74         9       0

[1000 rows x 4 columns]

In [116]:
df.replace(to_replace=[50,51,52,53], value= ['A', 'B', 'C', 'D'])

    Maths Physics Chemistry  Result
0      17      27        22       0
1      72      82        77       1
2      97      18        13       0
3       8      42        37       0
4      32      25        20       0
..    ...     ...       ...     ...
995     4      48        64       0
996    63      22        88       0
997    90      64        43       1
998    67      41         6       0
999    92      74         9       0

[1000 rows x 4 columns]

In [ ]:
df['Physics'].replace(to_replace=[50,51,52,53], value= ['A', 'B', 'C', 'D'], inplace = True)

/var/folders/my/qd9mcb891llg4w2fz82l_1nr0000gn/T/ipykernel_45756/3224400610.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Physics'].replace(to_replace=[50,51,52,53], value= ['A', 'B', 'C', 'D'], inplace = True)

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

In [120]:
df

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

In [121]:
df.replace('[A-Za-z]', 0)

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

## loc() function

In [122]:
df.iloc[1]

Maths        72
Physics      82
Chemistry    77
Result        1
Name: 1, dtype: int64

In [123]:
df.iloc[5]

Maths        15
Physics      73
Chemistry    68
Result        0
Name: 5, dtype: int64

In [124]:
df.loc[[5,6,7,8]]

   Maths  Physics  Chemistry  Result
5     15       73         68       0
6     63       67         62       1
7     97       70         65       1
8     57       93         88       1

In [125]:
df.loc[5, 'Physics']

np.int64(73)

In [126]:
df.loc[5:15, 'Chemistry']

5     68
6     62
7     65
8     88
9     53
10    31
11    17
12    67
13     8
14    54
15    60
Name: Chemistry, dtype: int64

In [127]:
df.loc[df['Physics']<50]

     Maths  Physics  Chemistry  Result
0       17       27         22       0
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
10      83       36         31       0
..     ...      ...        ...     ...
992     96       43         37       0
994     87       24         15       0
995      4       48         64       0
996     63       22         88       0
998     67       41          6       0

[477 rows x 4 columns]

In [128]:
df.loc[df['Physics']>80]

     Maths  Physics  Chemistry  Result
1       72       82         77       1
8       57       93         88       1
16       3       87         82       0
21      98       85         97       1
27      29       93          7       0
..     ...      ...        ...     ...
937     90       91         61       1
947    100       94         56       1
950      9       88         62       0
961     58       91         62       1
974     14       95         45       0

[167 rows x 4 columns]

In [129]:
df.loc[df['Physics']>80, ['Maths']]

     Maths
1       72
8       57
16       3
21      98
27      29
..     ...
937     90
947    100
950      9
961     58
974     14

[167 rows x 1 columns]

## iloc() function

In [ ]:
df.iloc[0]

In [ ]:
df.iloc[[0]]

In [130]:
df.iloc[:,0]

0      17
1      72
2      97
3       8
4      32
       ..
995     4
996    63
997    90
998    67
999    92
Name: Maths, Length: 1000, dtype: int64

In [131]:
df.iloc[:,1]

0      27
1      82
2      18
3      42
4      25
       ..
995    48
996    22
997    64
998    41
999    74
Name: Physics, Length: 1000, dtype: int64

In [132]:
df.iloc[0:5, 1]

0    27
1    82
2    18
3    42
4    25
Name: Physics, dtype: int64

In [133]:
df.iloc[0:5, 1:4]

   Physics  Chemistry  Result
0       27         22       0
1       82         77       1
2       18         13       0
3       42         37       0
4       25         20       0

## GroupBy() fucntion

In [158]:
branch_group = df.groupby(by = 'Branch')
branch_group

KeyError: 'Branch'

In [ ]:
branch_group.groups

In [ ]:
df.groupby(by = ['Branch', 'Section'])
branch_group.groups

In [ ]:
for group, data_frame in branch_group:
    print(group)
    print(data_frame)

## Merge() Function

In [ ]:
df1 = pd.DataFrame({'Roll No.':[1,2,3,4,5], 'Physics':[34,67,34,89,12]})
df1

   Roll No.  Physics
0         1       34
1         2       67
2         3       34
3         4       89
4         5       12

In [ ]:
df2 = pd.DataFrame({'Roll No.':[1,2,3,4,5], 'Chemistry':[78,33,39,81,90]})
df2

   Roll No.  Chemistry
0         1         78
1         2         33
2         3         39
3         4         81
4         5         90

In [ ]:
pd.merge(df1, df2, on = 'Roll No.')

   Roll No.  Physics  Chemistry
0         1       34         78
1         2       67         33
2         3       34         39
3         4       89         81
4         5       12         90

In [ ]:
pd.merge(df2, df1, on = 'Roll No.')

   Roll No.  Chemistry  Physics
0         1         78       34
1         2         33       67
2         3         39       34
3         4         81       89
4         5         90       12

In [ ]:
pd.merge(df1, df2)   # on - by default intersecting column is taken

   Roll No.  Physics  Chemistry
0         1       34         78
1         2       67         33
2         3       34         39
3         4       89         81
4         5       12         90

In [ ]:
df3 = pd.DataFrame({'Roll No.':[1,2,3,6,7], 'Physics':[34,67,34,89,12]})
df4 = pd.DataFrame({'Roll No.':[1,2,3,8,9], 'Chemistry':[34,67,34,89,12]})

In [ ]:
pd.merge(df3, df4)

   Roll No.  Physics  Chemistry
0         1       34         34
1         2       67         67
2         3       34         34

In [ ]:
pd.merge(df3, df4, how = 'left')

   Roll No.  Physics  Chemistry
0         1       34       34.0
1         2       67       67.0
2         3       34       34.0
3         6       89        NaN
4         7       12        NaN

In [ ]:
pd.merge(df3, df4, how = 'right')

   Roll No.  Physics  Chemistry
0         1     34.0         34
1         2     67.0         67
2         3     34.0         34
3         8      NaN         89
4         9      NaN         12

In [ ]:
pd.merge(df3, df4, how = 'outer')

   Roll No.  Physics  Chemistry
0         1     34.0       34.0
1         2     67.0       67.0
2         3     34.0       34.0
3         6     89.0        NaN
4         7     12.0        NaN
5         8      NaN       89.0
6         9      NaN       12.0

## concat() Function

In [ ]:
df1 = pd.DataFrame({'Roll No.':[1,2,3,4,5], 'Maths':[45,78,45,90,66], 'Physics':[33,67,12,90,44]})
df2 = pd.DataFrame({'Roll No.':[6,7,8,9,10], 'Maths':[78,73,45,90,69], 'Physics':[23,67,88,0,98]})
print(df1)
print(df2)

   Roll No.  Maths  Physics
0         1     45       33
1         2     78       67
2         3     45       12
3         4     90       90
4         5     66       44
   Roll No.  Maths  Physics
0         6     78       23
1         7     73       67
2         8     45       88
3         9     90        0
4        10     69       98

In [ ]:
df3 = pd.concat([df1, df2], ignore_index=True)
print(df3)

   Roll No.  Maths  Physics
0         1     45       33
1         2     78       67
2         3     45       12
3         4     90       90
4         5     66       44
5         6     78       23
6         7     73       67
7         8     45       88
8         9     90        0
9        10     69       98

## date and time

### date

In [159]:
import pandas as pd
import datetime as dt

In [160]:
today = dt.date(2021, 8, 22)

In [161]:
today.day

22

In [ ]:
today.month

In [ ]:
today.year

### datetime

In [ ]:
today = dt.datetime(2021, 8, 22, 17, 45, 51)

In [ ]:
print(today)

In [ ]:
today.hour

In [ ]:
today.minute

In [ ]:
today.second

### timestamp

In [164]:
pd.Timestamp('2021-12-25')

Timestamp('2021-12-25 00:00:00')

In [ ]:
pd.Timestamp('2019/02/13')

In [ ]:
pd.Timestamp('2020, 4, 21')

In [ ]:
pd.Timestamp('2020, 4, 21 18:33:12')

### datetime index

In [ ]:
dates = ['2019/12/22', '2012/8/22', '2015/2/22']

In [ ]:
pd.DatetimeIndex(dates)

In [ ]:
type(dates)

In [ ]:
dates[1]

In [ ]:
dates2 = [dt.date(2021, 9, 8), dt.date(2021, 9, 9), dt.date(2021, 9, 10)]

In [ ]:
dates2

In [ ]:
dateIndex = pd.DatetimeIndex(dates2)
dateIndex

In [ ]:
values = [12, 7, 30]
pd.Series(data=values, index=dateIndex)

### to_datetime()

In [ ]:
pd.to_datetime('2021, 1, 5')

In [ ]:
pd.to_datetime(dt.date(2001, 12, 12))

In [ ]:
pd.to_datetime(dt.datetime(2012, 2, 12, 18, 33, 12))

In [ ]:
dates = ['2019/12/22', '2012/8/22', '2015/2/22']
pd.to_datetime(dates)

In [ ]:
dates3 = pd.Series(
    ['December 22nd, 1999', '2019, 12, 12', "This is Date", 'Jan 5th, 2021'])
dates3

In [ ]:
pd.to_datetime(dates3, errors='coerce')  #invalid parsing will be set as NaT

In [ ]:
unixtime = [3244563, 3545463, 3242037, 7363236]
pd.to_datetime(unixtime, unit='s')